#version: "2"
version: "3.3"
services:
  backend:
    build: ./api-backend
    #restart: always
    restart: on-failure
    ports:
      - "8001:8001"
  frontend:
    build: ./api-frontend
    environment:
      API_BACKEND_URL: backend
      API_BACKEND_PORT: 8001
    #restart: always
    restart: on-failure
    depends_on:
      - backend
    ports: 
      - "8000:8000"
